### ISSUE TITLE
大佬你好。写得不错额，目前在线上项目中使用过吗？

### ISSUE THREAD

**Issue by 13120241790** [Caij/MMKVSharedPreferences#1]
MultiProcessListenerMMKVSharedPreferences 不用 只用 SimpleMMKVSharedPreferences  是不是也有夸进程 k v 的读取能力只是没有跨进程的数据变更的 listener 通知 ，可以这样理解吗？

**Comment by Caij** [comment]
已经在正式项目使用。MultiProcessListenerMMKVSharedPreferences主要是修改字段通知支持多进程，SimpleMMKVSharedPreferences通知不支持多进程。 数据读写是否跨进程只取决于你的传入参数mode值。
