### ISSUE TITLE
这个地方可能有点小问题

### ISSUE THREAD

**Issue by 13120241790** [Caij/MMKVSharedPreferences#3]
一般在页面上散着用是没有问题的，但是有时候想去集中管理去简化用法的时候就会产生问题详情如下：

例如下面代码我基于您的代码做了一个 KeyValueManager 的全局单例包装，put 的时候不需要再去 commit 或者 apply 。这时候全局只有一个 Editor 

    public void init(Context context, String sharedPreferencesName) {
        mContext = context;
        mPreferences = new MMKVSharedPreferencesFactory().getSharedPreferences(context, sharedPreferencesName, Context.MODE_PRIVATE);
        mEditor = mPreferences.edit();
    }

这时候 MMKVEdit 内的 keyValues 缓存就会越来越大，而且我每次去 commit 的时候 commitUpdate 方法就会遍历，即使我只去 commit 一个简单的 int 值。咱们的库的设计在集中管理使用的情况下也会去遍历所有的 keyValues 重新去操作 mmkv 的接口。不知道大佬有没有考虑过这个场景？有什么好的解决办法和意见吗？

**Comment by 13120241790** [comment]
当然了即使这种全局只 holder 一个 mPreferences 和 mEditor 的情况也不会出现数据错乱的问题，只是感觉更改一个值，会导致 keyValues 持有的所有键值对都去遍历。开销比较大

**Comment by 13120241790** [comment]
当然了即使这种全局只 holder 一个 mPreferences 和 mEditor 的情况也不会出现数据错乱的问题，只是感觉更改一个值，会导致 MMKVEdit 中 keyValues 持有的所有键值对都去遍历。开销比较大

**Comment by Caij** [comment]
非常不建议editor使用全局单例，全局保证一个sp即可。 你可以看看系统的实现，原理是类似的。
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/SharedPreferencesImpl.java

**Comment by 13120241790** [comment]
public final class EditorImpl implements Editor {
        private final Object mEditorLock = new Object();

        @GuardedBy("mEditorLock")
        private final Map<String, Object> mModified = new HashMap<>();
        ......
}

看了，源码的 EditorImpl 确实差不多， 我先整项目里面试试。看看大家伙的接受度怎么样，谢谢了
