### ISSUE TITLE
getAll()

### ISSUE THREAD

**Issue by 13120241790** [Caij/MMKVSharedPreferences#4]
Map<String, ?> all = preferences.getAll(); 
拿到的 value 是 ？，如果在外面想使用如何去遍历和拿到正确的类型？

                Set<String> keySet = preferences.getAll().keySet();
                for (String key : keySet) {
//                    if  {
//                    }
                }
                Map<String, ?> all = preferences.getAll();
                for (int i = 0; i < all.size(); i++) {
//                    if () {
//                    }
                }

**Comment by Caij** [comment]
新增了demo 更新代码

**Comment by 13120241790** [comment]
Thx ，I get it
